export CONFIG_MSM_TOUCH=m
export CONFIG_TOUCHSCREEN_FTS=y
export CONFIG_SEC_CMD=y
export CONFIG_TOUCHSCREEN_HIMAX_CHIPSET=y
export CONFIG_TOUCHSCREEN_CHIPONE_ICNL9958R=y
export CONFIG_TOUCHSCREEN_JADARD_CHIPSET=y