export CONFIG_MSM_TOUCH=m
export CONFIG_TOUCHSCREEN_FTS=y
export CONFIG_SEC_CMD=y
export CONFIG_TOUCHSCREEN_HIMAX_CHIPSET=y
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_I2C=y
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_CORE=y
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_TOUCH=y
export CONFIG_TOUCHSCREEN_GOODIX_BRL=y
export CONFIG_TOUCHSCREEN_FTS_DIRECTORY="focaltech_touch"
export CONFIG_FTS_TRUSTED_TOUCH=n
export CONFIG_QTS_ENABLE=y
